---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/default/requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: ghcr.io/hifis-net/ubuntu-systemd:22.04
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    command: /sbin/init
    security_opts:
      - seccomp:unconfined
    capabilities:
      - SYS_ADMIN
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer,yaml
    ssh_connection:
      pipelining: true
  playbooks:
    converge: playbook.yml
verifier:
  name: ansible
