---
- name: Verify MySQL installation and configuration
  hosts: all
  become: true
  tasks:
    - name: Check if MySQL service is running
      ansible.builtin.systemd:
        name: mysql
      register: mysql_service_status

    - name: Verify MySQL service is active
      ansible.builtin.assert:
        that:
          - mysql_service_status.status.ActiveState == "active"
        fail_msg: "MySQL service is not running"

    - name: Check MySQL version
      ansible.builtin.command: mysql --version
      register: mysql_version
      changed_when: false

    - name: Verify MySQL version output
      ansible.builtin.assert:
        that:
          - "'mysql' in mysql_version.stdout.lower()"
        fail_msg: "MySQL version check failed"

    - name: Test MySQL connection
      community.mysql.mysql_info:
        login_unix_socket: /var/run/mysqld/mysqld.sock
      register: mysql_info

    - name: Verify MySQL connection successful
      ansible.builtin.assert:
        that:
          - mysql_info.version is defined
        fail_msg: "Could not connect to MySQL"

    - name: Check if test database exists
      community.mysql.mysql_db:
        name: test_db
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
      check_mode: true
      register: test_db_check

    - name: Verify test database exists
      ansible.builtin.assert:
        that:
          - not test_db_check.changed
        fail_msg: "Test database was not created"

    - name: Check if test user exists
      community.mysql.mysql_user:
        name: test_user
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
      check_mode: true
      register: test_user_check

    - name: Verify test user exists
      ansible.builtin.assert:
        that:
          - not test_user_check.changed
        fail_msg: "Test user was not created"

    - name: Check MySQL configuration file
      ansible.builtin.stat:
        path: /etc/mysql/mysql.conf.d/99-custom.cnf
      register: mysql_config

    - name: Verify MySQL configuration file exists
      ansible.builtin.assert:
        that:
          - mysql_config.stat.exists
        fail_msg: "MySQL configuration file not found"
